# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e45d5d5e689bb87207119267c50e4b9bb62c2f9212259bb7fd2c8b00730b165dbc00f9f61514a6464b636a493103c5f353e97768f5fd2d672f061f68c8e30363

test:
  secret_key_base: 79fbc6c49a4d37323234ebc9b48fd6f27fca9d45e104972df65d404bf77208c92cdfc03a7e4aa5e9bbe59d40a67453fe24e1905c44bc88838fa82bdf5128554e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
